# Site
repository: heonie/heonie.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kookheon Kim
title: Senior Software Engineer
email: heonie@gmail.com
website: https://heonie.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: heonie
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: heonie9292
linkedin_username: kookheon-kim
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: heonie.pe.kr
    icon: fas fa-globe
    url: https://heonie.pe.kr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  16년째 서비스를 개발하고 있는 풀스택 웹 개발자입니다.<br/>
  대기업에서 1000+ 스마트 TV 앱이 사용하는 웹 앱 프레임워크와 오픈소스 개발 과제를 설계/개발했고, 신규 제품 컨셉을 프로토타이핑하고 제품화에 기여했으며, 글로벌 사용자를 가진 TV 클라우드 게이밍 서비스를 개발했습니다.<br/>
  현재는 스타트업의 초기멤버로서 클라우드 기반의 동시편집을 지원하는 웹 3D 에디터를 개발하고 있으며, 이를 통해 네이티브 기술 기반이던 회사를 웹 기반의 B2B/B2C SaaS 회사로 탈바꿈하는데 기여하고 있습니다.<br/>
  초기 아이디어부터 상용화 단계까지 각 비즈니스 단계에 맞는 최적의 개발 방법론과 기술 스택을 선택하여 문제를 해결하는데 능숙하며, 주로 사용하는 기술은 <mark>React</mark>, <mark>Node.js</mark>, <mark>TypeScript</mark>, <mark>AWS</mark>입니다.<br/>
  팀원의 성장을 돕고 조직과 개인의 발전을 얼라인하는 팀 운영을 지향합니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
